#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

gcloud auth activate-service-account $GKE_SERVICE_ACCOUNT_NAME --key-file=$GOOGLE_APPLICATION_CREDENTIALS
gcloud config set project $GKE_PROJECT_NAME
gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_ZONE


python manage.py migrate
uvicorn config.asgi:application --host 0.0.0.0 --reload
