# Generated by Django 3.1.7 on 2021-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Celery ID for the task that was run', max_length=255, unique=True, verbose_name='Task ID')),
                ('task_name', models.CharField(help_text='Name of the task that was run', max_length=255, null=True, verbose_name='Task name')),
                ('task_args', models.TextField(help_text='JSON represantation of the positional arguments', null=True, verbose_name='Positional arguments')),
                ('task_kwargs', models.TextField(help_text='JSON represantation of the named arguments', null=True, verbose_name='Named arguments')),
                ('status', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', help_text='Current state of the task being run', max_length=50, verbose_name='Task status')),
                ('worker', models.CharField(default=None, help_text='Worker that executes the tasks', max_length=100, null=True, verbose_name='Worker')),
                ('result', models.TextField(default=None, editable=False, help_text='The data retuned by the task', null=True, verbose_name='Task result')),
                ('traceback', models.TextField(default=True, help_text='Traceback from the task', null=True, verbose_name='Traceback')),
                ('date_done', models.DateTimeField(auto_now=True, help_text='DateTime field when the task finished(in UTC).', verbose_name='Task completion datetime')),
            ],
            options={
                'verbose_name': 'Task Result',
                'verbose_name_plural': 'Task results',
                'ordering': ['-date_done'],
            },
        ),
    ]
