# Generated by Django 3.1.7 on 2021-05-09 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_taskresult_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresult",
            name="user",
            field=models.ForeignKey(
                default=None,
                help_text="User who ran the task",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
