# Generated by Django 3.1.7 on 2021-07-25 18:06

from django.db import migrations, models
import django.db.models.deletion
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("tasks", "0004_taskresult_task_beat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repo_url",
                    models.CharField(
                        max_length=255, verbose_name="Url of the GitHub repository"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, verbose_name="Name of the GitHub repository"
                    ),
                ),
                (
                    "image_name",
                    models.CharField(
                        help_text="Name of the Docker image inside user namespace",
                        max_length=255,
                        unique=True,
                        verbose_name="Image name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTask",
            fields=[
                (
                    "periodictask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "task_type",
                    models.PositiveSmallIntegerField(verbose_name=utils.enums.TaskEnum),
                ),
                (
                    "image",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_usertask_related",
                        related_query_name="tasks_usertasks",
                        to="tasks.taskimage",
                    ),
                ),
            ],
            bases=("django_celery_beat.periodictask",),
        ),
    ]
