# Generated by Django 3.1.7 on 2021-08-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskimage_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskimage',
            name='command',
            field=models.CharField(default='/', help_text='Command to execute after image startup.', max_length=255),
            preserve_default=False,
        ),
    ]
