# Generated by Django 3.1.7 on 2021-09-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210813_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='exception',
            field=models.TextField(default=True, help_text='Exception from the task', null=True, verbose_name='Exception'),
        ),
    ]
