# Generated by Django 3.1.7 on 2022-02-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_auto_20220216_2149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskresult",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "PENDING"),
                    (1, "RECEIVED"),
                    (2, "STARTED"),
                    (3, "SUCCESS"),
                    (4, "FAILURE"),
                    (5, "REVOKED"),
                    (6, "REJECTED"),
                    (7, "RETRY"),
                    (8, "IGNORED"),
                ],
                default=0,
                help_text="Current state of the task being run",
                verbose_name="Task status",
            ),
        ),
    ]
