# Generated by Django 3.1.7 on 2022-02-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_auto_20220216_2227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskresult",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Received"),
                    (2, "Started"),
                    (3, "Success"),
                    (4, "Failure"),
                    (5, "Revoked"),
                    (6, "Rejected"),
                    (7, "Retry"),
                    (8, "Ignored"),
                ],
                default=0,
                help_text="Current state of the task being run",
                verbose_name="Task status",
            ),
        ),
    ]
