# Generated by Django 3.1.7 on 2022-02-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_usertask_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_usertask_related",
                related_query_name="tasks_usertasks",
                to="tasks.taskimage",
            ),
        ),
    ]
