# Generated by Django 3.1.7 on 2022-03-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_auto_20220305_1148"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskimage",
            old_name="full_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="taskimage",
            old_name="repo_url",
            new_name="repository",
        ),
    ]
