# Generated by Django 3.1.7 on 2022-03-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_taskimage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskimage",
            name="secret_key",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
    ]
