# Generated by Django 3.1.7 on 2022-03-27 15:35

from django.db import migrations, models
import shigoto_q.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_taskimage_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskimage",
            name="secret_key",
            field=models.CharField(
                blank=True,
                default=shigoto_q.tasks.models.generate_secret,
                max_length=512,
                null=True,
            ),
        ),
    ]
