apiVersion: apps/v1
kind: Deployment
metadata:
  name: shigoto-django
  labels:
    component: django
spec:
  replicas: 1
  selector:
    matchLabels:
      component: django
  template:
    metadata:
      labels:
        component: django
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: django
          image: bogdanp3trovic/shigoto_q_production_django
          ports:
            - containerPort: 8000
          args:
            - /start
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: django-secret
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  key: WEBHOOK_SECRET
                  name: django-secret
            - name: LIVE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: LIVE_SECRET_KEY
                  name: django-secret
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_PASSWORD
                  name: django-configmap
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: SENTRY_DSN
                  name: django-secret
            - name: TEST_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: TEST_SECRET_KEY
                  name: django-secret
            - name: CELERY_FLOWER_USER
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_USER
                  name: django-configmap
            - name: DOCKER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_SERVICE_URL
                  name: django-configmap
            - name: IPYTHONDIR
              valueFrom:
                configMapKeyRef:
                  key: IPYTHONDIR
                  name: django-configmap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-configmap
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-configmap
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgres-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-configmap
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: django-configmap
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: SENTRY_ENVIRONMENT
                  name: django-configmap
            - name: USE_DOCKER
              valueFrom:
                configMapKeyRef:
                  key: USE_DOCKER
                  name: django-configmap
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
