apiVersion: apps/v1
kind: Deployment
metadata:
  name: shigoto-react
  labels:
    component: react
spec:
  replicas: 1
  selector:
    matchLabels:
      component: react
  template:
    metadata:
      labels:
        component: react
    spec:
      containers:
        - name: shigoto-react
          image: bogdanp3trovic/shigoto_q_production_react
          ports:
            - containerPort: 3000

