apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  labels:
    type: hostpath
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: sharedpv
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/sharedpv"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: hostpath

