# Generated by Django 3.1.7 on 2021-04-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("users", "0009_auto_20210422_1858"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interval",
            field=models.ManyToManyField(to="django_celery_beat.IntervalSchedule"),
        ),
    ]
