# Generated by Django 3.1.7 on 2021-04-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('users', '0010_user_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clocked',
            field=models.ManyToManyField(to='django_celery_beat.ClockedSchedule'),
        ),
        migrations.AddField(
            model_name='user',
            name='solar',
            field=models.ManyToManyField(to='django_celery_beat.SolarSchedule'),
        ),
    ]
