# Generated by Django 3.1.7 on 2021-05-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210424_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_tasks',
        ),
    ]
