# Generated by Django 3.1.7 on 2022-02-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20210609_1801"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="task",
        ),
    ]
