# Generated by Django 3.1.7 on 2022-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("users", "0016_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="clocked",
            field=models.ManyToManyField(
                null=True, to="django_celery_beat.ClockedSchedule"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="crontab",
            field=models.ManyToManyField(
                null=True, to="django_celery_beat.CrontabSchedule"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="interval",
            field=models.ManyToManyField(
                null=True, to="django_celery_beat.IntervalSchedule"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="solar",
            field=models.ManyToManyField(
                null=True, to="django_celery_beat.SolarSchedule"
            ),
        ),
    ]
