# Generated by Django 3.1.7 on 2022-03-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20220301_2032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="zip_code",
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
