# Generated by Django 3.1.7 on 2022-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_auto_20220305_1705"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_auth_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
