# Generated by Django 3.1.7 on 2022-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_user_two_factor_auth_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
