# Generated by Django 3.1.7 on 2022-04-14 21:12

from django.db import migrations, models
import django.db.models.deletion
import shigoto_q.kubernetes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=shigoto_q.kubernetes.models.generate_secret,
                        max_length=512,
                        unique=True,
                    ),
                ),
                ("kind", models.IntegerField()),
                ("name", models.CharField(max_length=512)),
                ("metadata", models.TextField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docker.dockerimage",
                    ),
                ),
            ],
        ),
    ]
