# Generated by Django 3.1.7 on 2022-05-04 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kubernetes', '0005_auto_20220504_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
