# Generated by Django 3.1.7 on 2022-05-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kubernetes", "0009_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="ingress",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="kubernetes.ingress",
            ),
        ),
    ]
