# Generated by Django 3.1.7 on 2022-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes', '0010_auto_20220521_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
