# Generated by Django 3.1.7 on 2021-09-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(default='production', max_length=120)),
                ('repository', models.CharField(default='backend', max_length=120)),
                ('notes', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
