# Generated by Django 3.1.7 on 2021-09-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shigoto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminconfig",
            name="base_url",
            field=models.CharField(default="http://shigoto.live", max_length=56),
        ),
    ]
