# Generated by Django 3.1.7 on 2021-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubprofile",
            name="token",
            field=models.CharField(default="", max_length=128),
        ),
    ]
