# Generated by Django 3.1.7 on 2021-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_repository_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
