# Generated by Django 3.1.7 on 2022-04-02 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shigoto_q.docker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DockerImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repository",
                    models.CharField(
                        max_length=255, verbose_name="Github repository url"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Github repository name"
                    ),
                ),
                (
                    "image_name",
                    models.CharField(
                        help_text="Name of the Docker image inside user namespace",
                        max_length=255,
                        unique=True,
                        verbose_name="Image name",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        help_text="Command to execute after image startup.",
                        max_length=255,
                        verbose_name="Command to execute",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        default=shigoto_q.docker.models.generate_secret,
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
