# Generated by Django 3.1.7 on 2022-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=128)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Discord'), (1, 'Slack')])),
            ],
        ),
    ]
