# Generated by Django 3.1.7 on 2022-05-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_webhookevent_webhookobserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookobserver",
            name="events",
            field=models.ManyToManyField(to="integrations.WebhookEvent"),
        ),
    ]
