name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - uses: psf/black@stable
        with:
          args: "--check --exclude '^.*\b(migrations)\b.*$' shigoto_q"
