name: CD

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the stack
        run: docker-compose -f production.yml build

      - name: Tag Docker images
        run: |
          docker tag shigoto_q_production_django ${{ secrets.DOCKERHUB_USERNAME }}/sgt-production-backend:${{ steps.vars.outputs.sha_short }}
          docker tag shigoto_q_production_postgres ${{ secrets.DOCKERHUB_USERNAME }}/sgt-production-db:${{ steps.vars.outputs.sha_short }}
          docker tag shigoto_q_production_celerybeat ${{ secrets.DOCKERHUB_USERNAME }}/sgt-production-celerybeat:${{ steps.vars.outputs.sha_short }}
          docker tag shigoto_q_production_celeryworker ${{ secrets.DOCKERHUB_USERNAME }}/sgt-production-celeryworker:${{ steps.vars.outputs.sha_short }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sgt-production-backend:${{ steps.vars.outputs.sha_short }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sgt-production-db:${{ steps.vars.outputs.sha_short }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sgt-production-celerybeat:${{ steps.vars.outputs.sha_short }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sgt-production-celeryworker:${{ steps.vars.outputs.sha_short }}
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
