name: CD

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GIT_SHA: $(git rev-parse HEAD)
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the stack
        run: docker-compose -f production.yml build

      - name: Tag Docker images 
        run: | 
          docker tag shigoto_q_production_django ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_django:$GIT_SHA
          docker tag shigoto_q_production_postgres ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_postgres:$GIT_SHA
          docker tag shigoto_q_production_celerybeat ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_celerybeat:$GIT_SHA
          docker tag shigoto_q_production_celeryworker ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_celeryworker:$GIT_SHA

      - name: Push Docker images 
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_postgres:$GIT_SHA
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_django:$GIT_SHA
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_celerybeat:$GIT_SHA
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_celeryworker:$GIT_SHA
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Shigoto-Q/sgt-infrastructure 
          event-type: build-successful
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
