export const TASK_CREATION_SUCCESS = "TASK_CREATED_SUCCESS"
export const TASK_CREATION_FAILED = "TASK_CREATION_FAILED"
export const TASK_RAN_SUCCESS = "TASK_RAN_SUCCESS"
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS"
